apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: demo-stable-policies
  name: demo-stable-policies-app
  namespace: policies
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - demo-stable-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  labels:
    app: demo-stable-policies
  name: demo-stable-policies-chan
  namespace: policies
spec:
  pathname: https://github.com/bstrauss84/cluster-management.git
  type: GitHub
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-stable-policies
  name: demo-stable-policies-placement
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: local-cluster
      operator: In
      values:
      - "true"
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: policygenerator/policy-sets/in-development/CM-Configuration-Management/policies-generators
  labels:
    app: demo-stable-policies
  name: demo-stable-policies-sub
  namespace: policies
spec:
  channel: policies/demo-stable-policies-chan
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-stable-policies-placement
