apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: cluster-banner
spec:
  text: $(Text)
  backgroundColor: $(BackgroundColor)
  color: $(Color)
  linkURL: $(LinkURL)
  linkText: $(LinkText)
