apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: custom-notification
spec:
  text: ENVIRONMENT-CLUSTER
  backgroundColor: #FF0000
  color: #FFFFFF
  linkURL: ""
  linkText: ""
