apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: enable-user-workload-monitoring
  namespace: openshift-monitoring
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - enable-user-workload-monitoring
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/user-workload-monitoring/configs
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: enable-user-workload-monitoring
  name: enable-user-workload-monitoring-subscription-1
  namespace: openshift-monitoring
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: enable-user-workload-monitoring-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: enable-user-workload-monitoring
  name: enable-user-workload-monitoring-placement-1
  namespace: openshift-monitoring
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
