apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: environment-banner
  namespace: openshift-console
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - environment-banner
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/cluster-configuration/ocp4-interface-customization/console-banners/sbx
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: environment-banner
  name: environment-banner-subscription-1
  namespace: openshift-console
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: environment-banner-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: environment-banner
  name: environment-banner-placement-1
  namespace: openshift-console
spec:
  clusterSelector:
    matchLabels:
      'environment': 'sbx'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/cluster-configuration/ocp4-interface-customization/console-banners/mgmt
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: environment-banner
  name: environment-banner-subscription-2
  namespace: openshift-console
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: environment-banner-placement-2
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: environment-banner
  name: environment-banner-placement-2
  namespace: openshift-console
spec:
  clusterSelector:
    matchLabels:
      'environment': 'mgmt'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/cluster-configuration/ocp4-interface-customization/console-banners/prod
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: environment-banner
  name: environment-banner-subscription-3
  namespace: openshift-console
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: environment-banner-placement-3
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: environment-banner
  name: environment-banner-placement-3
  namespace: openshift-console
spec:
  clusterSelector:
    matchLabels:
      'environment': 'prod'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/cluster-configuration/ocp4-interface-customization/console-banners/dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: environment-banner
  name: environment-banner-subscription-4
  namespace: openshift-console
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: environment-banner-placement-4
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: environment-banner
  name: environment-banner-placement-4
  namespace: openshift-console
spec:
  clusterSelector:
    matchLabels:
      'environment': 'dev'
