apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: example-user-workload-monitoring-app
  namespace: ns1
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - example-user-workload-monitoring-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/user-workload-monitoring/example-uwm-app
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: example-user-workload-monitoring-app
  name: example-user-workload-monitoring-app-subscription-1
  namespace: ns1
spec:
  channel: ggithubcom-bstrauss84-cluster-managemen-ns/ggithubcom-bstrauss84-cluster-managemen
  placement:
    placementRef:
      kind: PlacementRule
      name: example-user-workload-monitoring-app-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: example-user-workload-monitoring-app
  name: example-user-workload-monitoring-app-placement-1
  namespace: ns1
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
