apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
bases:
- ../../base

patches:
- patch.yaml

configMapGenerator:
- name: env-config
  literals:
  - Text=DEV-CLUSTER
  - BackgroundColor=yellow
  - Color=black
  - LinkURL=https://www.example.com
  - LinkText=Learn More
