apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-request-default
  namespace: openshift-config
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: system:image-builders
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: system:deployers
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: view
    namespace: ${PROJECT_NAME}
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: openshift-resource-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        openshift.io/image-tags: "8"
      type: openshift.io/ImageStream
