apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-request-default
  namespace: openshift-config
objects:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: openshift-resource-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        openshift.io/image-tags: "8"
      type: openshift.io/ImageStream
