apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: redhat-operator-index
spec:
  repositoryDigestMirrors:
  - mirrors:
    - registry.myexample.com:5000/example-repo2
    source: registry.redhat.io/example-repo2
  - mirrors:
    - registry.myexample.com:5000/example-repo2
    source: registry.redhat.io/example-repo2
